spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gestor_tareas?currentSchema=task_manager}
    username: ${SPRING_DATASOURCE_USERNAME:gestor_tareas_app}
    password: ${SPRING_DATASOURCE_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: task_manager
        jdbc:
          time_zone: UTC

  sql:
    init:
      mode: never
